version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "35:e4:27:dc:db:71:53:84:8c:20:46:e4:9a:92:65:88"
      - checkout
      - run:
          name: Install
          command: |
            yarn install
      - run:
          name: Build
          command: |
            yarn build
